

[server]
    PullPort=":10067"
    HttpPort=":10068"

[logger]
Level ="debug"
Stacktrace=true
AddCaller =true
Debug =true
FileName ="./stdout.ws.json"
WarnFileName ="./stderr.ws.json"
MaxSize =100
MaxAge =10
MaxBackup =10
Async =true
#是否 输出json格式的数据，JSON格式相对于console格式，不方便阅读，但是对机器更加友好
Json=false
[etcd]
endpoints=["192.168.2.99:2379"]
keyPrefix="proxy"