# yaml 配置
version: "3.3"
services:
  mysql8:
    image: "mysql:latest"
    ports:
      - "33061:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/test.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "test"
      MYSQL_PASSWORD: "root1234"
    volumes:
      - ./resource/test.sql:/data/application/test.sql
  bubble_app:
    build: .
    command: sh -c "./wait-for.sh mysql8:3306 -- ./ginintegrate --config=./config/config.yaml"
    depends_on:
      - mysql8
    ports:
      - "12000:12000"