

[server]
    port="0.0.0.0:9992"
    timeOut=20000

[bucket]
    BucketCount =512
    JobChanSize =100
    DispatchChanSize =100
    BucketFanOutCount =32
[connection]
  #写频率毫秒
   WriteRate=500
  #连接超时事件
   TimeOut=200000000
   #是否压缩 使用defalte协议压缩
   IsCompress=false
   #写缓存的大小
   writeBufSize=1024
[logger]
    Level ="debug"
    Stacktrace=true
    AddCaller =true
    Debug =true
    FileName ="./stdout.ws.json"
    WarnFileName ="./stderr.ws.json"
    MaxSize =100
    MaxAge =10
    MaxBackup =10
    Async =true
    #是否 输出json格式的数据，JSON格式相对于console格式，不方便阅读，但是对机器更加友好
    Json=false
[proxy]
    addrs = ["192.168.2.99:10067"]
